FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    clang \
    valgrind \
    gdb \
    make \
    cmake \
    git \
    man \
    curl \
    wget \
    vim \
    libreadline-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
